version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: proximity.pihole
    environment:
      TZ: Europe/London
      WEBPASSWORD: ""
    volumes:
      - /docker/pihole:/etc/pihole/
      - /docker/pihole/dnsmasq:/etc/dnsmasq.d/
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
    cap_add:
      - NET_ADMIN
    restart: always

  unbound:
    container_name: unbound
    image: mvance/unbound:latest
    volumes:
      - /docker/unbound:/opt/unbound/etc/unbound/
    ports:
      - 5335:53/udp
      - 5335:53/tcp
    restart: always

  wg-easy:
    environment:
      PASSWORD: T1jan333
      WG_HOST: home.cityplug.co.uk
      WG_PORT: 24792
      WG_PERSISTENT_KEEPALIVE: 25
      WG_DEFAULT_ADDRESS: 10.25.50.x
      WG_DEFAULT_DNS: 192.168.50.253
      WG_ALLOWED_IPS: 0.0.0.0/0, 192.168.50.1/24
    image: weejewel/wg-easy:latest
    container_name: wireguard
    volumes:
      - /docker/wireguard/:/etc/wireguard
    ports:
      - "24792:51820/udp"
      - "24792:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1